apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "presto.name" . }}-catalog
  labels:
    app: {{ template "presto.name" . }}
    chart: {{ template "presto.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ toYaml .Values.catalog | indent 2 }}

---
